language: go
go:
- '1.10'
before_install:
- openssl aes-256-cbc -K $encrypted_c4027621f6ad_key -iv $encrypted_c4027621f6ad_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

after_success:
- pwd
- ls -l

addons:
  ssh_known_hosts: 150.109.105.160
